/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Devices": {                                     "en": "Devices",                                         "de": "Geräte",                                          "ru": "Устройства",                                      "pt": "Aparelhos",                                       "nl": "Apparaten",                                       "fr": "Dispositifs",                                     "it": "dispositivi",                                     "es": "Dispositivos",                                    "pl": "Urządzenia",                                      "zh-cn": "设备"},
    "Enabled": {                                     "en": "Enabled",                                         "de": "Aktiviert",                                       "ru": "Активированно",                                   "pt": "Ativado",                                         "nl": "Geactiveerd",                                     "fr": "Activé",                                          "it": "attivato",                                        "es": "Activado",                                        "pl": "Aktywowany",                                      "zh-cn": "活性"},
    "Extended Info": {                               "en": "Extended Info",                                   "de": "Extended Info",                                   "ru": "Расширенная информация",                          "pt": "Extended Info",                                   "nl": "Extended Info",                                   "fr": "Extended Info",                                   "it": "Extended Info",                                   "es": "Extended Info",                                   "pl": "Extended Info",                                   "zh-cn": "扩展信息"},
    "IP Address": {                                  "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "IP Адрес",                                        "pt": "IP Address",                                      "nl": "IP Address",                                      "fr": "IP Address",                                      "it": "IP Address",                                      "es": "IP Address",                                      "pl": "IP Address",                                      "zh-cn": "IP地址"},
    "Interval[ms]:": {                               "en": "Ping interval[ms]",                               "de": "Ping Intervall[ms]",                              "ru": "Интервал опроса[мс]:",                            "pt": "Ping interval[ms]",                               "nl": "Ping interval[ms]",                               "fr": "Ping interval[ms]",                               "it": "Ping interval[ms]",                               "es": "Ping interval[ms]",                               "pl": "Ping interval[ms]",                               "zh-cn": "ping间隔[ms]"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Name",                                            "nl": "Name",                                            "fr": "Name",                                            "it": "Name",                                            "es": "Name",                                            "pl": "Name",                                            "zh-cn": "名称"},
    "No host name in state name:": {                 "en": "No host name in state name:",                     "de": "Kein Hostnamen im Zustandsnamen:",                "ru": "Имена состояний без имени хоста:",                "pt": "No host name in state name:",                     "nl": "No host name in state name:",                     "fr": "No host name in state name:",                     "it": "No host name in state name:",                     "es": "No host name in state name:",                     "pl": "No host name in state name:",                     "zh-cn": "状态名称中没有主机名："},
    "PING adapter settings": {                       "en": "PING adapter settings",                           "de": "PING Adapter-Einstellungen",                      "ru": "Настройки драйвера PING",                         "pt": "PING adapter settings",                           "nl": "PING adapter settings",                           "fr": "PING adapter settings",                           "it": "PING adapter settings",                           "es": "PING adapter settings",                           "pl": "PING adapter settings",                           "zh-cn": "PING适配器设置"},
    "Ping addresses": {                              "en": "IP addresses to ping",                            "de": "IP Adresse für Monitoring",                       "ru": "Список IP адресов для мониторинга",               "pt": "IP addresses to ping",                            "nl": "IP addresses to ping",                            "fr": "IP addresses to ping",                            "it": "IP addresses to ping",                            "es": "IP addresses to ping",                            "pl": "IP addresses to ping",                            "zh-cn": "ping IP地址"},
    "Ping settings": {                               "en": "Ping settings",                                   "de": "PING Einstellungen",                              "ru": "Настройки PING",                                  "pt": "Ping settings",                                   "nl": "Ping settings",                                   "fr": "Ping settings",                                   "it": "Ping settings",                                   "es": "Ping settings",                                   "pl": "Ping settings",                                   "zh-cn": "ping设置"},
    "Use name": {                                    "en": "Use name",                                        "de": "Use name",                                        "ru": "Использовать Имя",                                "pt": "Use name",                                        "nl": "Use name",                                        "fr": "Use name",                                        "it": "Use name",                                        "es": "Use name",                                        "pl": "Use name",                                        "zh-cn": "使用名称"},
    "tooltip_interval": {                            "en": "Polling interval in ms",                          "de": "Abfrage Intervall in ms",                         "ru": "Интервал опроса в миллисекундах",                 "pt": "Polling interval in ms",                          "nl": "Polling interval in ms",                          "fr": "Polling interval in ms",                          "it": "Polling interval in ms",                          "es": "Polling interval in ms",                          "pl": "Polling interval in ms",                          "zh-cn": "轮询间隔（毫秒）"},
    "tooltip_noHostname": {                          "en": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "de": "Inkludiere kein Hostnamen in die Zustandsnamen:  ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "ru": "Убрать имя хоста из имён состояний: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "pt": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "nl": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "fr": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "it": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "es": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "pl": "Do not include the host name into state's names: ping.0.127_0_0_1 / ping.0.host.127_0_0_1", "zh-cn": "不要将主机名包含在州名称中：ping.0.127_0_0_1 / ping.0.host.127_0_0_1"},
};